#pragma once
#include <glad\glad.h>

namespace Plutonium
{
	/* Defines the API sources for OpenGL log messages. */
	enum class OpenGLSource : GLenum
	{
#if defined(GL_DEBUG_SOURCE_API)
		/* Calls to the OpenGL API. */
		Basic = GL_DEBUG_SOURCE_API,
#endif
#if defined(GL_DEBUG_SOURCE_WINDOW_SYSTEM)
		/* Calls to the window-system API. */
		Window = GL_DEBUG_SOURCE_WINDOW_SYSTEM,
#endif
#if defined(GL_DEBUG_SOURCE_SHADER_COMPILER)
		/* A shader compiler. */
		Shader = GL_DEBUG_SOURCE_SHADER_COMPILER,
#endif
#if defined(GL_DEBUG_SOURCE_THIRD_PARTY)
		/* Any third party application associated with OpenGL. */
		ThirdParty = GL_DEBUG_SOURCE_THIRD_PARTY,
#endif
#if defined(GL_DEBUG_SOURCE_APPLICATION)
		/* Any message generated by the user application. */
		User = GL_DEBUG_SOURCE_APPLICATION,
#endif
#if defined(GL_DEBUG_SOURCE_OTHER)
		/* Miscellaneous. */
		Other = GL_DEBUG_SOURCE_OTHER
#endif
	};
}